# Generated by Django 2.2 on 2020-05-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nick_name',
            field=models.CharField(max_length=50, verbose_name='昵称'),
        ),
    ]
