# Generated by Django 2.2 on 2020-05-24 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200524_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
