# Generated by Django 2.2 on 2020-05-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200524_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='add_time',
        ),
    ]
