# Generated by Django 2.2 on 2020-05-22 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='地名')),
                ('name_particular', models.CharField(max_length=50, verbose_name='具体地名')),
                ('introduction', models.CharField(max_length=1000, verbose_name='简介')),
                ('altitude', models.CharField(max_length=100, verbose_name='经度')),
                ('longtitude', models.CharField(max_length=100, verbose_name='纬度')),
            ],
            options={
                'verbose_name': '迁徙地标',
                'verbose_name_plural': '迁徙地标',
            },
        ),
    ]
