# Generated by Django 2.2 on 2020-05-22 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='人名')),
                ('lineage_level', models.IntegerField(verbose_name='世系代数')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('untested_info', models.CharField(max_length=1000, verbose_name='待考证信息')),
            ],
            options={
                'verbose_name': '世系信息',
                'verbose_name_plural': '世系信息',
            },
        ),
    ]
