# Generated by Django 2.2 on 2020-05-22 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_lineagetree'),
    ]

    operations = [
        migrations.CreateModel(
            name='GravesMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='墓址名')),
                ('introduction', models.CharField(max_length=1000, verbose_name='简介')),
                ('altitude', models.CharField(max_length=1000, verbose_name='经度')),
                ('longtitude', models.CharField(max_length=1000, verbose_name='纬度')),
            ],
            options={
                'verbose_name': '坟茔信息',
                'verbose_name_plural': '坟茔信息',
            },
        ),
    ]
