# Generated by Django 2.2 on 2020-05-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_gravesmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineagetree',
            name='lineage_level',
            field=models.CharField(max_length=50, verbose_name='世系代数'),
        ),
    ]
