# Generated by Django 2.2 on 2020-05-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_lineagetree_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geoposition',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='geoposition',
            name='longtitude',
        ),
        migrations.RemoveField(
            model_name='geoposition',
            name='name',
        ),
        migrations.RemoveField(
            model_name='geoposition',
            name='name_particular',
        ),
        migrations.AddField(
            model_name='geoposition',
            name='from_address',
            field=models.CharField(choices=[('xuan_wei', '宣威县'), ('fang_zhu', '放珠镇'), ('mai_bai', '马摆乡'), ('guan_zhai', '马摆官寨'), ('hou_cao', '马摆后槽'), ('da_fang', '大方县'), ('dong_di', '董地乡田坝寨'), ('zhi_jin', '织金县')], default='', max_length=50, verbose_name='迁出地'),
        ),
        migrations.AddField(
            model_name='geoposition',
            name='migrate_order',
            field=models.CharField(choices=[('order1', '第一次迁徙'), ('order2', '第二次迁徙'), ('order3', '第三次迁徙'), ('order4', '第四次迁徙'), ('order5', '第五次迁徙'), ('order6', '第六次迁徙'), ('order7', '第七次迁徙')], default='', max_length=50, verbose_name='迁徙序列'),
        ),
        migrations.AddField(
            model_name='geoposition',
            name='now_address',
            field=models.CharField(choices=[('xuan_wei', '宣威县'), ('fang_zhu', '放珠镇'), ('mai_bai', '马摆乡'), ('guan_zhai', '马摆官寨'), ('hou_cao', '马摆后槽'), ('da_fang', '大方县'), ('dong_di', '董地乡田坝寨'), ('zhi_jin', '织金县')], default='', max_length=50, verbose_name='现居地'),
        ),
        migrations.AddField(
            model_name='geoposition',
            name='now_address_particular',
            field=models.CharField(default='', max_length=100, verbose_name='具体地名'),
        ),
        migrations.AddField(
            model_name='geoposition',
            name='to_address',
            field=models.CharField(choices=[('xuan_wei', '宣威县'), ('fang_zhu', '放珠镇'), ('mai_bai', '马摆乡'), ('guan_zhai', '马摆官寨'), ('hou_cao', '马摆后槽'), ('da_fang', '大方县'), ('dong_di', '董地乡田坝寨'), ('zhi_jin', '织金县')], default='', max_length=50, verbose_name='迁入地'),
        ),
        migrations.AddField(
            model_name='geoposition',
            name='to_altitude',
            field=models.CharField(default='', max_length=100, verbose_name='迁入地经度'),
        ),
        migrations.AddField(
            model_name='geoposition',
            name='to_longtitude',
            field=models.CharField(default='', max_length=100, verbose_name='迁入地纬度'),
        ),
        migrations.AddField(
            model_name='gravesmap',
            name='belong_to_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='history.LineageTree'),
        ),
        migrations.AddField(
            model_name='lineagetree',
            name='introduction',
            field=models.CharField(blank=True, max_length=1000, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='lineagetree',
            name='lineage_area',
            field=models.CharField(choices=[('m_zhangfang', '马摆长房'), ('m_erfang', '马摆二房'), ('m_yaofang', '马摆幺房'), ('b_fangzhu', '毕节放珠支系')], default='', max_length=50, verbose_name='所属世系'),
        ),
        migrations.AlterField(
            model_name='geoposition',
            name='introduction',
            field=models.CharField(blank=True, max_length=1000, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='lineagetree',
            name='father',
            field=models.CharField(max_length=50, verbose_name='父亲姓名'),
        ),
        migrations.AlterField(
            model_name='lineagetree',
            name='lineage_level',
            field=models.CharField(choices=[('order1', '一世'), ('order2', '二世'), ('order3', '三世'), ('order4', '四世'), ('order5', '五世'), ('order6', '六世'), ('order7', '七世'), ('order8', '八世'), ('order9', '九世'), ('order10', '十世'), ('order11', '十一世'), ('order12', '十二世')], default='', max_length=50, verbose_name='世系代数'),
        ),
        migrations.AlterField(
            model_name='lineagetree',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='lineagetree',
            name='untested_info',
            field=models.CharField(blank=True, max_length=1000, verbose_name='待考证信息'),
        ),
    ]
