# Generated by Django 2.2 on 2020-05-24 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20200524_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoposition',
            name='from_address',
            field=models.CharField(choices=[('unknow', '未知'), ('xuan_wei', '宣威县'), ('fang_zhu', '放珠镇'), ('mai_bai', '马摆乡'), ('guan_zhai', '马摆官寨'), ('hou_cao', '马摆后槽'), ('da_fang', '大方县'), ('dong_di', '董地乡田坝寨'), ('zhi_jin', '织金县')], default='', max_length=50, verbose_name='迁出地'),
        ),
        migrations.AlterField(
            model_name='geoposition',
            name='now_address',
            field=models.CharField(choices=[('unknow', '未知'), ('xuan_wei', '宣威县'), ('fang_zhu', '放珠镇'), ('mai_bai', '马摆乡'), ('guan_zhai', '马摆官寨'), ('hou_cao', '马摆后槽'), ('da_fang', '大方县'), ('dong_di', '董地乡田坝寨'), ('zhi_jin', '织金县')], default='', max_length=50, verbose_name='现居地'),
        ),
        migrations.AlterField(
            model_name='geoposition',
            name='to_address',
            field=models.CharField(choices=[('unknow', '未知'), ('xuan_wei', '宣威县'), ('fang_zhu', '放珠镇'), ('mai_bai', '马摆乡'), ('guan_zhai', '马摆官寨'), ('hou_cao', '马摆后槽'), ('da_fang', '大方县'), ('dong_di', '董地乡田坝寨'), ('zhi_jin', '织金县')], default='', max_length=50, verbose_name='迁入地'),
        ),
        migrations.AlterField(
            model_name='gravesmap',
            name='belong_to_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='history.LineageTree', verbose_name='世系中所属'),
        ),
    ]
