# Generated by Django 2.2 on 2020-05-24 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20200524_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='gravesmap',
            name='lineage_area',
            field=models.CharField(choices=[('m_zhangfang', '马摆长房'), ('m_erfang', '马摆二房'), ('m_yaofang', '马摆幺房'), ('b_fangzhu', '毕节放珠支系')], default='', max_length=50, verbose_name='所属世系'),
        ),
        migrations.AlterField(
            model_name='gravesmap',
            name='belong_to_user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='history.LineageTree', verbose_name='世系姓名'),
        ),
        migrations.AlterField(
            model_name='gravesmap',
            name='name',
            field=models.CharField(max_length=50, verbose_name='墓址'),
        ),
        migrations.CreateModel(
            name='HusbandToWife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('lineage_area', models.CharField(choices=[('m_zhangfang', '马摆长房'), ('m_erfang', '马摆二房'), ('m_yaofang', '马摆幺房'), ('b_fangzhu', '毕节放珠支系')], default='', max_length=50, verbose_name='所属世系')),
                ('lineage_level', models.CharField(choices=[('order1', '一世'), ('order2', '二世'), ('order3', '三世'), ('order4', '四世'), ('order5', '五世'), ('order6', '六世'), ('order7', '七世'), ('order8', '八世'), ('order9', '九世'), ('order10', '十世'), ('order11', '十一世'), ('order12', '十二世')], default='', max_length=50, verbose_name='世系代数')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('father', models.CharField(max_length=50, verbose_name='父亲姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=6, verbose_name='性别')),
                ('introduction', models.CharField(blank=True, max_length=1000, verbose_name='简介')),
                ('untested_info', models.CharField(blank=True, max_length=1000, verbose_name='待考证信息')),
                ('belong_to_who', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='history.LineageTree', verbose_name='配偶姓名')),
            ],
            options={
                'verbose_name': '娶入嫁出',
                'verbose_name_plural': '娶入嫁出',
            },
        ),
    ]
