# Generated by Django 2.2 on 2020-05-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20200524_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='husbandtowife',
            name='marriage_to',
            field=models.CharField(choices=[('marriage_in', '娶入'), ('marriage_out', '嫁出')], default='', max_length=50, verbose_name='嫁娶'),
        ),
    ]
